ifeq ($(TESTCASE), TCOPYIN)
DEFINES += -DGM_ROW=$(row) -DGM_COL=$(col) -DTR_ROW=$(trow) -DTR_COL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TCOPYOUT)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TADD)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TEXP)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TCOPY)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TROWMAX)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TROWMAXEXPAND)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TROWSUM)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TROWSUMEXPAND)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), MATMUL)
DEFINES += -DGM=$(M) -DGN=$(N) -DGK=$(K) -DTM=$(TM) -DTN=$(TN) -DTK=$(TK)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_M$(M)_N$(N)_K$(K)_tM$(TM)_tN$(TN)_tK$(TK).elf
endif

ifeq ($(TESTCASE), CubeVecTrans)
DEFINES += -DGM=$(M) -DGN=$(N) -DGK=$(K) -DTM=$(TM) -DTN=$(TN) -DTK=$(TK)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_M$(M)_N$(N)_K$(K)_tM$(TM)_tN$(TN)_tK$(TK).elf
endif

ifeq ($(TESTCASE), TRESHAPE)
DEFINES += -DROW=$(ROW) -DCOL=$(COL) -DRROW=$(RROW) -DRCOL=$(RCOL)
TARGET = $(ELF_HEAD)_$(TESTCASE)_ROW$(ROW)_COL$(COL)_RROW$(RROW)_RCOL$(RCOL).elf
endif

ifeq ($(TESTCASE), TEXTRACT)
DEFINES += -DROW=$(ROW) -DCOL=$(COL) -DEROW=$(EROW) -DECOL=$(ECOL) -DRIDX=$(RIDX) -DCIDX=$(CIDX)
TARGET = $(ELF_HEAD)_$(TESTCASE)_R$(ROW)_C$(COL)_ER$(EROW)_EC$(ECOL)_RI$(RIDX)_CI$(CIDX).elf
endif

ifeq ($(TESTCASE), TASSEMBLE)
DEFINES += -DROW=$(ROW) -DCOL1=$(COL1) -DCOL2=$(COL2) -DCOL3=$(COL3)
TARGET = $(ELF_HEAD)_$(TESTCASE)_R$(ROW)_C1$(COL1)_C2$(COL2)_C3$(COL3).elf
endif

ifeq ($(TESTCASE), fa_tileop)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TADDCAST)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TABS)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TADDMASK)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TAND)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TEXPANDCOL)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TEXPANDROW)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TEXPANDSCALAR)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TDIV)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TMUL)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TSUB)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TCAST)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TFILLPAD)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TGATHER)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TSELECT)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TTRANS)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TMAKERANGE)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), TOR)
DEFINES += -DROW=$(row) -DCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_$(MODE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), MGATHER)
DEFINES += -DGROW=$(row) -DGCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifeq ($(TESTCASE), MSCATTER)
DEFINES += -DGROW=$(row) -DGCOL=$(col) -DTROW=$(trow) -DTCOL=$(tcol)
TARGET = $(ELF_HEAD)_$(TESTCASE)_r$(row)_c$(col)_tr$(trow)_tc$(tcol).elf
endif

ifneq ($(MODE), )
   ifeq ($(TESTCASE), MATMUL)
      DEFINES += -DMODE=$(MODE)
   else
      DEFINES += -DMODE=\"$(MODE)\"
   endif
endif

SRC_FILE +=  $(TEST_ROOT)/$(CASE_SRC_DIR)/$(TESTCASE).cpp
CATEGORY_ROOT := $(abspath ../..)
include ../../benchmarks/common/Makefile.common
