COMMON_MAKEFILE := $(abspath $(lastword $(MAKEFILE_LIST)))
TEST_ROOT := $(abspath $(dir $(COMMON_MAKEFILE))/..)
ROOT := $(abspath $(TEST_ROOT)/..)
CATEGORY := $(patsubst $(TEST_ROOT)/%,%,$(CURDIR))
CATEGORY_NAME := $(subst /,_,$(CATEGORY))
OBJ_ROOT := $(abspath $(ROOT)/output)
CASE_SRC_DIR := $(CATEGORY)/src
ELF_DIR := $(OBJ_ROOT)/$(CATEGORY)/elf
SRC_DIR := $(shell dirname $(SRC_FILE))
OBJ_DIR := $(OBJ_ROOT)/$(CASE_SRC_DIR)
ELF_HEAD := $(ELF_DIR)/$(CATEGORY_NAME)

OBJ := $(patsubst %.cpp, %.o, $(subst $(SRC_DIR), $(OBJ_DIR), $(SRC_FILE)))
OBJ := $(patsubst %.c, %.o, $(OBJ))
OBJ := $(patsubst %.s, %.o, $(OBJ))

PLAT ?= linx

ifeq ($(PLAT), cpu)
DEFINES += -D__cpu_sim__
# wget http://10.50.84.202:8888/other/bisa_share/toolchain/open_source/clang-x86/clang%2Bllvm-15.0.4-x86_64-linux-gnu-rhel-8.4.tar.xz
COMPILER_DIR ?= /usr/bin
AS = $(COMPILER_DIR)/clang
CC = $(COMPILER_DIR)/clang
CXX = $(COMPILER_DIR)/clang++
LINK = $(COMPILER_DIR)/clang++
DUMP = $(COMPILER_DIR)/llvm-objdump
COPY = $(COMPILER_DIR)/llvm-objcopy
CC_O = -c -O3
CC_VER ?= -std=c++20
else ifeq ($(PLAT), arm_sme)
DEFINES += -D__ARM_FEATURE_SME
# wget http://10.50.84.202:8888/other/bisa_share/toolchain/open_source/clang-x86/clang%2Bllvm-15.0.4-x86_64-linux-gnu-rhel-8.4.tar.xz
COMPILER_DIR ?= /usr/bin
AS = $(COMPILER_DIR)/clang
CC = $(COMPILER_DIR)/clang
CXX = $(COMPILER_DIR)/clang++
LINK = $(COMPILER_DIR)/clang++
DUMP = $(COMPILER_DIR)/llvm-objdump
COPY = $(COMPILER_DIR)/llvm-objcopy
CC_O = -c -O3
CC_VER ?= -std=c++20
else ifeq ($(PLAT), linx)
DEFINES += -D__linx
# wget http://example.com/linx_blockisa_llvm_musl.tar.gz
COMPILER_DIR ?= /usr/bin
AS = $(COMPILER_DIR)/clang
CC = $(COMPILER_DIR)/clang 
CXX = $(COMPILER_DIR)/clang++
LINK = $(COMPILER_DIR)/clang++
DUMP = $(COMPILER_DIR)/llvm-objdump
COPY = $(COMPILER_DIR)/llvm-objcopy
CC_O = -c -mlxbc -fenable-matrix -O2 -mllvm -enable-all-vector-as-tilereg=true
CC_VER ?= -std=c++20
CC_LINK += -nostartfiles $(ROOT)/test/common/_start.s
endif

ifeq ($(PY_LIB), on)
CC_O += -fPIC
CC_LINK += -shared
INCLUDE += -I/usr/include/python3.10 -I/usr/local/lib/python3.10/dist-packages/pybind11/include \
           -I$(HOME)/.local/lib/python3.10/site-packages/pybind11/include
endif

ifeq ($(LIB), on)
CC_O += -fPIC
CC_LINK += -shared
endif

INCLUDE += -I$(ROOT)/include -I$(ROOT)/test/common -I$(ROOT)/test/common/src -I$(ROOT)/test/kernels/src -I$(ROOT)/kernels
QEMU = /remote/lms60/c00622284/qemu/LinxBlockModel/build/qemu-linx

CC_O_ALL = $(CC_O) $(CC_VER) $(CC_OPTS)
# $(info "TEST_ROOT is $(TEST_ROOT)")
# $(info "ELF_HEAD is $(ELF_HEAD)")
# $(info "OBJ_ROOT is $(OBJ_ROOT)")
# $(info "SRC_DIR is $(SRC_DIR)")
# $(info "OBJ_DIR is $(OBJ_DIR)")
# $(info "OBJ is $(OBJ)")
# $(info "COMM_OBJ is $(COMM_OBJ)")
# $(info "SRC_FILE is $(SRC_FILE)")
# $(info "TARGET is $(TARGET)")

all: pre_work $(TARGET)

diss: pre_work $(TARGET)
	$(DUMP) -dl $(TARGET) > $(TARGET).diss

sim: pre_work $(TARGET)
	$(QEMU) -run-supertest -blk_optimize force_tb_chained $(TARGET)

debug: pre_work $(TARGET)
	$(QEMU) -run-supertest -blk_optimize force_tb_chained -d in_asm,exec,nochain,linxmem -D run.log $(TARGET) 

$(OBJ_DIR)%.o: $(SRC_DIR)%.cpp
	@mkdir -p $(shell dirname $@)
	$(CXX) $(CC_O_ALL) $(INCLUDE) $(DEFINES) $< -o $@

$(OBJ_DIR)%.o: $(SRC_DIR)%.c
	@mkdir -p $(shell dirname $@)
	$(CC) $(CC_O_ALL) $(INCLUDE) $(DEFINES) $< -o $@

$(OBJ_DIR)%.o: $(SRC_DIR)%.s
	@mkdir -p $(shell dirname $@)
	$(AS) $(CC_O_ALL) $(INCLUDE) $(DEFINES) $< -o $@

$(OBJ_DIR)%.o: $(COMM_SRC_DIR)%.s
	@mkdir -p $(shell dirname $@)
	$(AS) $(CC_O_ALL) $(INCLUDE) $(DEFINES) $< -o $@

$(TARGET): $(OBJ) $(COMM_OBJ)
	@mkdir -p $(shell dirname $@)
	$(LINK) $(CC_LINK) $(COMM_OBJ) $(OBJ) -o $@

pre_work:
	@mkdir -p $(OBJ_DIR)
	@mkdir -p $(ELF_DIR)

clean:
#	rm -rf $(OBJ_ROOT)/*/*.o
	@find $(OBJ_ROOT) -type f -name "*.o" -exec rm -rf {} \;

clean_all:
	@rm -rf $(OBJ_ROOT)

.PHONY: all diss sim clean clean_all pre_work
